# Generated by Django 4.0.2 on 2022-05-24 08:37

import auth_.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_.models.UserManager()),
            ],
        ),
    ]
